// The TextMate grammar of `.hatch`, generated from the core's own language registry (D1, D2):
// one region per language the core reads, from its `# match <name>` to the next hunk, with
// that language's grammar inside. The names come from the core; only which VS Code grammar
// paints each language is ours (SCOPES). Run by `npm run grammar`, checked by a test.

/** The core's adapter name → the TextMate scope and language id VS Code paints it with. */
export const SCOPES = {
  cpp: { scope: 'source.cpp', id: 'cpp' },
  c: { scope: 'source.c', id: 'c' },
  objc: { scope: 'source.objc', id: 'objective-c' },
  python: { scope: 'source.python', id: 'python' },
  javascript: { scope: 'source.js', id: 'javascript' },
  typescript: { scope: 'source.ts', id: 'typescript' },
  tsx: { scope: 'source.tsx', id: 'typescriptreact' },
  rust: { scope: 'source.rust', id: 'rust' },
  java: { scope: 'source.java', id: 'java' },
  go: { scope: 'source.go', id: 'go' },
  // VS Code has no Kotlin grammar of its own: without an extension that brings one, the
  // body stays uncolored — not an error
  kotlin: { scope: 'source.kotlin', id: 'kotlin' },
};

const H = '#{1,6}[ \\t]*';
const heading = (word, name) => ({ match: `(?i)^${H}${word}:?[ \\t]*$`, name });
const escapeRe = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

/** `aliases`: the core's adapter name → every name `# match` accepts for it. */
export function grammarFor(aliases) {
  const languages = Object.keys(aliases).sort();
  const missing = languages.filter((name) => SCOPES[name] === undefined);
  if (missing.length > 0) throw new Error(`no TextMate scope for the core's language(s): ${missing.join(', ')}`);

  const operators = [
    { match: '(?<=^    |\\s)\\\\(?=\\\\*(?:\\.\\.\\.|>>>|<<<)(?:\\s|$))', name: 'constant.character.escape.hatch' },
    { match: '(?<=^    |\\s)(\\.\\.\\.)(?=\\s|$)', name: 'keyword.operator.gap.hatch' },
    { match: '(?<=^    |\\s)(>>>|<<<)(?=\\s|$)', name: 'keyword.operator.mark.hatch' },
  ];
  const until = `^(?=${H}(?:match|note):?(?:[ \\t]|$))`;

  const repository = {};
  const hunks = [];
  for (const name of languages) {
    const { scope, id } = SCOPES[name];
    const names = [...aliases[name]].sort((a, b) => b.length - a.length).map(escapeRe).join('|');
    const embedded = `meta.embedded.block.${id}`;
    repository[`hunk-${name}`] = {
      begin: `(?i)^(${H}match:?)[ \\t]+(${names})[ \\t]*$`,
      beginCaptures: { 1: { name: 'keyword.control.match.hatch' }, 2: { name: 'entity.name.type.language.hatch' } },
      end: until,
      patterns: [
        {
          begin: `(?i)^(${H}patch:?)[ \\t]*$`,
          beginCaptures: { 1: { name: 'keyword.control.patch.hatch' } },
          end: `(?i)^(${H}end)[ \\t]*$`,
          endCaptures: { 1: { name: 'keyword.control.end.hatch' } },
          contentName: embedded,
          patterns: [{ include: scope }],
        },
        heading('end', 'keyword.control.end.hatch'),
        ...operators,
        { begin: '^(?=    )', end: '$', contentName: embedded, patterns: [...operators, { include: scope }] },
      ],
    };
    hunks.push({ include: `#hunk-${name}` });
  }

  repository['hunk-any'] = {
    begin: `(?i)^(${H}match:?)(?:[ \\t]+(\\S+))?[ \\t]*$`,
    beginCaptures: { 1: { name: 'keyword.control.match.hatch' }, 2: { name: 'invalid.illegal.language.hatch' } },
    end: until,
    patterns: [heading('patch', 'keyword.control.patch.hatch'), heading('end', 'keyword.control.end.hatch'), ...operators],
  };

  return {
    $schema: 'https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json',
    name: 'Hatch',
    scopeName: 'text.hatch',
    comment: 'Generated by scripts/build-grammar.mjs from the core\'s language registry — do not edit by hand.',
    patterns: [{ include: '#header' }, { include: '#note' }, ...hunks, { include: '#hunk-any' }],
    repository: {
      header: {
        begin: '\\A(?=[A-Za-z][\\w-]*:[ \\t])',
        end: '^[ \\t]*$',
        patterns: [
          {
            match: '^(Hatch|Target)(:)[ \\t]+(.*)$',
            captures: { 1: { name: 'keyword.other.header.key.hatch' }, 2: { name: 'punctuation.separator.hatch' }, 3: { name: 'string.unquoted.header.value.hatch' } },
          },
          {
            match: '^([A-Za-z][\\w-]*)(:)[ \\t]+(.*)$',
            captures: { 1: { name: 'variable.other.header.key.hatch' }, 2: { name: 'punctuation.separator.hatch' }, 3: { name: 'comment.line.header.value.hatch' } },
          },
        ],
      },
      note: {
        begin: `(?i)^(${H}note:?)[ \\t]*$`,
        beginCaptures: { 1: { name: 'keyword.control.note.hatch' } },
        end: `(?i)^(${H}end)[ \\t]*$`,
        endCaptures: { 1: { name: 'keyword.control.end.hatch' } },
        contentName: 'comment.block.note.hatch',
      },
      ...repository,
    },
  };
}

/** The `embeddedLanguages` of package.json for the grammar above. */
export function embeddedLanguages() {
  return Object.fromEntries(Object.values(SCOPES).map(({ id }) => [`meta.embedded.block.${id}`, id]));
}
